#: import FadeTransition kivy.uix.screenmanager.FadeTransition

ScreenManagement:
	transition: FadeTransition()
	MainScreen:
	AnotherScreen:

<MainScreen>:
	name: 'main'
	Button:
		on_release: app.root.current = 'other'
		text: 'Открыть холст'
		font_size: 50

<AnotherScreen>:
	name: 'other'

	FloatLayout:
		Painter
		Button:
			color: 1,1,1,1
			font_size: 20
			size_hint: 0.2,0.1
			text: 'Завершить'
			on_release: app.root.current = 'main'
			pos_hint: {'right':1, 'top':1}
