<ItemLabel@Label>:
    font_size: 40

<LoginScreen>:
    cols: 2

    GridLayout:
        rows: 2

        BoxLayout:
            orientation: 'horizontal'

            ItemLabel:
                text: 'Логин'
            TextInput:
                multiline: False

        BoxLayout:
            orientation: 'horizontal'

            ItemLabel:
                text: 'Пароль'
            TextInput:
                multiline: False
